services:
  - type: web
    name: reqline-parser-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CAN_LOG_ENDPOINT_INFORMATION
        value: false
